export const ADD_POST = 'ADD_POST';
export const REMOVE_POST = 'REMOVE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DISPLAY_POST = 'DISPLAY_POST';
export const SAMPLE_POST = 'SAMPLE_POST';
export const SAMPLE_UPDATE_POST = "SAMPLE_UPDATE_POST";
export const SAMPLE_REMOVE_POST = "SAMPLE_REMOVE_POST";
export const FILTERED_POST = "FILTERED_POST";